In [1]:
import torch

In [4]:
#张量表示数值组成的数组，数组可能有多个维度

x = torch.arange(12)
x 


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [7]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2,3,4))
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
x = torch.tensor([1.0,2,3,4])
x   #这里写1.0就是浮点型

tensor([1., 2., 3., 4.])

In [15]:
torch.exp(x)


tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)     #cat合并，dim=0就是在行合并，dim=1就是在列合并

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y #用逻辑运算符构建二元张量


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
#广播机制
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b  #要求维度相同，a编程3X2矩阵，b也变成3X2矩阵，在相加，，，，，补0

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
#这里的Y的指针变了
before = id(Y)
Y = Y + X
id(Y) == before  # 用+=不会发生变化

False

In [21]:
#执行原地操作
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1868133596832
id(Z): 1868133596832


In [22]:
import os
#创建人工数据集
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:    
    f.write('NumRooms,Alley,Price\n')  #列名
    f.write('NA,Pave,127500\n')  #每行表示一个数据样本 
    f.write('2,NA,10600\n')
    f.write('4,NA,17800\n')
    f.write('NA,NA,14000\n')


In [23]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN   10600
2       4.0   NaN   17800
3       NaN   NaN   14000


In [24]:
#处理缺失数据，插值或者删除
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]   #把所有行，第0...1列放到inputs，，，把所有行，第2列放到outputs
inputs = inputs.fillna(inputs.mean())   #fillna--对所有的NA填一个值均值，第2列是string类型
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\86183\AppData\Local\Temp\ipykernel_12488\1694781144.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [26]:
inputs = pd.get_dummies(inputs,dummy_na = True)
print(inputs)   #将NA视为一个类别，分成两类


   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [27]:
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)  #数值转化为张量格式
X,y  #python默认转为float64，但是这样计算会比较慢，一般用float32

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500,  10600,  17800,  14000]))