In [1]:
import torch
x =torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [4]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [5]:
A_sum_axis0 =A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

In [6]:
a = torch.ones([2,5,4])
a.shape

torch.Size([2, 5, 4])

In [10]:
a.sum(axis=1,keepdim=True).shape
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [13]:
#计算y关于x的梯度之前，需要一个地方来存储梯度
x.requires_grad_(True)  #等价于  x=torch.arange(4.0,requires_grad=True) 
x.grad   #默认值是None

In [14]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
#通过调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad


tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad == 4*x

tensor([True, True, True, True])

In [17]:
#在默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [18]:
#对非标量调用backward需要传入一个‘gradient’参数，该参数指定微分函数关于自己的梯度
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [22]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()    #先对z求和，使 z成为标量，再对x求导数，这样不会有影响。本质上是将向量对向量求梯度，通过加权求和的方式，转换成标量对向量求梯度
x.grad

tensor([0., 1., 4., 9.])

In [23]:
x.grad.zero_()
y.sum().backward()    
x.grad == 2 * x

tensor([True, True, True, True])

In [26]:
def f(a):
    b = a*2
    while b.norm() < 1000:  # b的额欧几里得范数
        b = b*2
    if b.sum() > 0:
        c = b
    else:
        c = 100*b
    return c
a = torch.randn(size=(),requires_grad = True)  #size等于空是标量

d = f(a)
d.backward()

a.grad == d/a

tensor(True)