In [2]:
#基本概率论

import torch
from torch.distributions import multinomial
#加plt.show()


In [7]:
fair_probs = torch.ones([6]) / 6
fair_probs  #意思是每个元素被取到的概率
#multinomial可以根据给定权重对数组进行多次采样，返回采样后的元素下标
multinomial.Multinomial(1,fair_probs).sample()  #抽取一个样本，传入一个概率向量


tensor([1., 0., 0., 0., 0., 0.])

In [8]:
#同时抽取多个样本
multinomial.Multinomial(10, fair_probs).sample()

tensor([2., 0., 0., 2., 3., 3.])

In [9]:
# 将结果存储为32位浮点数以进行除法
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000  # 相对频率作为估计值

tensor([0.1730, 0.1690, 0.1530, 0.1730, 0.1610, 0.1710])

In [12]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))  #500组，每组抽取10个
counts


tensor([[0., 2., 2., 4., 0., 2.],
        [2., 2., 1., 1., 4., 0.],
        [1., 1., 5., 3., 0., 0.],
        ...,
        [3., 1., 0., 4., 0., 2.],
        [1., 2., 1., 3., 1., 2.],
        [2., 0., 3., 1., 4., 0.]])

In [13]:
#cumsum这个函数的功能是返回给定axis上的累计和，dim=0，就是0轴上
cum_counts = counts.cumsum(dim=0)
cum_counts


tensor([[  0.,   2.,   2.,   4.,   0.,   2.],
        [  2.,   4.,   3.,   5.,   4.,   2.],
        [  3.,   5.,   8.,   8.,   4.,   2.],
        ...,
        [844., 856., 848., 785., 833., 814.],
        [845., 858., 849., 788., 834., 816.],
        [847., 858., 852., 789., 838., 816.]])

In [14]:
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)
estimates


tensor([[0.0000, 0.2000, 0.2000, 0.4000, 0.0000, 0.2000],
        [0.1000, 0.2000, 0.1500, 0.2500, 0.2000, 0.1000],
        [0.1000, 0.1667, 0.2667, 0.2667, 0.1333, 0.0667],
        ...,
        [0.1695, 0.1719, 0.1703, 0.1576, 0.1673, 0.1635],
        [0.1693, 0.1719, 0.1701, 0.1579, 0.1671, 0.1635],
        [0.1694, 0.1716, 0.1704, 0.1578, 0.1676, 0.1632]])

In [15]:
torch.set_figsize((6, 4.5))
for i in range(6):
    torch.plt.plot(estimates[:, i].numpy(),
                 label=("P(die=" + str(i + 1) + ")"))
torch.plt.axhline(y=0.167, color='black', linestyle='dashed')
torch.plt.gca().set_xlabel('Groups of experiments')
torch.plt.gca().set_ylabel('Estimated probability')
torch.plt.legend()
plt.show()

AttributeError: module 'torch' has no attribute 'set_figsize'